### ISSUE TITLE
Doubt : using type uint32_t as type ImageDirectoryEntry

### ISSUE THREAD

**Issue by boddumanohar** [merces/pev#106]
in line [317](https://github.com/merces/pev/blob/master/src/readpe.c#L317) of readpe.c, a function `pe_directory_name` whose function definition is 
```
const char *pe_directory_name(ImageDirectoryEntry entry);
```
is used. But in the line 317 when we have passed `uint32_t` values into `pe_directory_name` function,  and the program ran happily. 

Why did it work when we have passed `uint32_t` when `ImageDirectoryEntry` is actually expected.

**Comment by jweyrich** [comment]
Hi Manohar! Thank you for posting here.

The code works because `ImageDirectoryEntry ` is defined as an `enum` in https://github.com/merces/libpe/blob/cbc1a47a86ad81f2f8ad96d51894ab678797fbe5/directories.h#L31, which is basically an integral type that can represent all values from the declared enumeration.

The magic is that C supports implicit casts, and that's what's happening in the line you mentioned. The `uint32_t` type is being implicitly converted to a `ImageDirectoryEntry` value, which is basically an `int` (actually, it's implementation-defined - by compilers - but  it's guaranteed to support the value range specified in the enum type).
If you try to cast a number that's out of the range of the enum values, you should get an error or warning from the compiler (depending on compilation flags).

**Comment by jweyrich** [comment]
I'm closing the issue for now. Let us know if you have other doubts.
