### ISSUE TITLE
Download version 0.71

### ISSUE THREAD

**Issue by diogoleal** [merces/pev#86]
In documentation is referenced version 0.71, but in sourceforge and github find only version 0.70.

Links for reference
http://sourceforge.net/projects/pev/files/
http://pev.sourceforge.net/doc/manual/en_us/ch01s02.html
http://pev.sourceforge.net/doc/manual/en_us/

**Comment by jweyrich** [comment]
I suppose this is a bug in the docs as v0.71 hasn't been tagged yet. Mostly because there are 2 bugs (namely #77 and #79) that should have been addressed prior to releasing v0.71, but we couldn't manage to fix them, yet. Maybe it's time for us to push the new version as it is, and postpone the fixes that are holding back the release of other important changes.

@merces: What do you think?

**Comment by merces** [comment]
I totally agree, @jweyrich.
Thanks, @diogoleal for the bug report.

**Comment by merces** [comment]
Fixed in the [online documentation](http://pev.sourceforge.net/doc/manual/en_us/).

Thanks!
